#!/bin/bash
#
BASE="~/.config/openbox"
redshift -P -O 3400 &
# killall picom; picom --animations --animation-window-mass 0.5 --animation-stiffness 230.0 --animation-for-open-window slide-left --animation-dampening 21.0 &
# killall picom; picom &
killall xcompmgr; xcompmgr -c -t-5 -l-5 -r6 -o1 -fF -I.07 -O.07 -D2 -C &
# if xrandr -q | egrep VGA | egrep connected -q; then
#         { xrandr --newmode 1600 118.25  1600 1696 1856 2112  900 903 908 934 -hsync +vsync; xrandr --addmode VGA1 1600; xrandr --output VGA1 --mode 1600 --primary --output LVDS1 --off; } &
# fi
nitrogen --restore &
killall lxpolkit; lxpolkit &
killall polybar; polybar bar -c ${BASE}/polybar -r &
xset led named "Scroll Lock" &
xwinwrap -g 1920x1080+0+0 -ni -ov -- mpv --loop-file=inf --speed=1 -wid WID ~/pictures/nfsub.gif &
# xwinwrap -g 1920x1080+0+0 -ni -ov -- mpv --loop-file=inf --speed=1 -wid WID ~/pictures/fizz.ultra.gif &
