#!/bin/bash
#
BASE="~/.config/openbox"
Terminal="xfce4-terminal"
Filemanager="pcmanfm"
Rofi="rofi -modi drun,run -show drun -icon-theme 'Papirus-Dark' -show-icons"
Lock="slock"
UpVol="amixer -q sset Master 2%+ unmute"
DownVol="amixer -q sset Master 2%- unmute"
Screenshot="xfce4-screenshooter -f"
WScreenshot="xfce4-screenshooter -w"
SScreenshot="xfce4-screenshooter -r"
animatedWallpaper="bash ${BASE}/animatedWallpaper.sh"

cat << SXHKDFILE > /tmp/sxhkd
# apps
super + Return
	${Terminal}

super + r
	${Rofi}

super + e
	${Filemanager}

super + l
	${Lock}

F8
	${UpVol}

F7
	${DownVol}

super + F10
	${Screenshot}

ctrl + F10
	${SScreenshot}

alt + F10
	${WScreenshot}

super + F12
	${animatedWallpaper}

super + shift + F12
	bash ${BASE}/autostart

super + shift + {e,r}
	openbox --{exit,restart}

SXHKDFILE

redshift -P -O 3400 &
# killall picom; picom --animations --animation-window-mass 0.5 --animation-stiffness 230.0 --animation-for-open-window slide-left --animation-dampening 21.0 &
# killall picom; picom &
killall xcompmgr; xcompmgr -c -t-5 -l-5 -r6 -o1 -fF -I.07 -O.07 -D2 -C &
nitrogen --restore &
killall lxpolkit; lxpolkit &
killall polybar; polybar bar -c ${BASE}/polybar -r &
killall plank; plank &
xset led named "Scroll Lock" &
xwinwrap -g 1920x1080+0+0 -ni -ov -- mpv --loop-file=inf --speed=1 -wid WID ~/pictures/nfsub.gif &
killall sxhkd; sxhkd -c /tmp/sxhkd &
killall lxpolkit; lxpolkit &
killall xdotool; bash ${BASE}/hc.sh &
# xwinwrap -g 1920x1080+0+0 -ni -ov -- mpv --loop-file=inf --speed=1 -wid WID ~/pictures/fizz.ultra.gif &
