#!/bin/bash

hc() { herbstclient "$@"; }

hc emit_hook reload

# remove all existing keybindings
hc keyunbind --all

Mod=Mod4    # Use alt as the main modifier
Terminal="xfce4-terminal"
Filemanager="pcmanfm"
Rofi="rofi -modi drun,run -show drun -icon-theme 'Papirus-Dark' -show-icons"
Lock="slock"
UpVol="amixer -q sset Master 2%+ unmute"
DownVol="amixer -q sset Master 2%- unmute"
Screenshot="xfce4-screenshooter -f"
WScreenshot="xfce4-screenshooter -w"
SScreenshot="xfce4-screenshooter -r"
BLUE="#005577"
CYAN="#1793d1"
ORANGE="#ff9b82"
GREY="#444444"


########### APPS ############

redshift -P -O 3400 &
killall picom; picom --animations --animation-window-mass 0.5 --animation-stiffness 230.0 --animation-for-open-window zoom --animation-dampening 21.0 &

if xrandr -q | egrep VGA | egrep connected -q; then
	{ xrandr --newmode 1600 118.25  1600 1696 1856 2112  900 903 908 934 -hsync +vsync; xrandr --addmode VGA1 1600; xrandr --output VGA1 --mode 1600 --primary --output LVDS1 --off; } &
fi
nitrogen --restore &
killall lxpolkit; lxpolkit &
killall polybar; polybar bar -c ~/.config/herbstluftwm/polybar -r &


############# APPS ############
hc keybind $Mod-Return spawn ${Terminal}
hc keybind $Mod-r spawn ${Rofi}
hc keybind $Mod-e spawn ${Filemanager}
hc keybind $Mod-l spawn ${Lock}
hc keybind F8 spawn ${UpVol}
hc keybind F7 spawn ${DownVol}
hc keybind F10 spawn ${Screenshot}
hc keybind $Mod-F10 spawn ${Screenshot}
hc keybind $Mod-Control-F10 spawn ${SScreenshot}
hc keybind $Mod-Mod1-F10 spawn ${WScreenshot}

# keybindings
# basic movement in tiling and floating mode
# focusing clients
hc keybind $Mod-Right cycle_all +1
hc keybind $Mod-Left cycle_all -1
hc keybind $Mod-Down  focus down
hc keybind $Mod-Up    focus up

# moving clients in tiling and floating mode
hc keybind $Mod-Shift-Left  shift left
hc keybind $Mod-Shift-Down  shift down
hc keybind $Mod-Shift-Up    shift up
hc keybind $Mod-Shift-Right shift right

# splitting frames
# create an empty frame at the specified direction
hc keybind $Mod-comma       split   bottom  0.5
hc keybind $Mod-period       split   right   0.5
# hc keybind $Mod-Control-space split explode

# resizing frames and floating clients
resizestep=0.02
hc keybind $Mod-Control-Left    resize left +$resizestep
hc keybind $Mod-Control-Down    resize down +$resizestep
hc keybind $Mod-Control-Up      resize up +$resizestep
hc keybind $Mod-Control-Right   resize right +$resizestep

# tags
tag_names=( {1..9} )
tag_keys=( {1..9} 0 )

hc rename default "${tag_names[0]}" || true
for i in "${!tag_names[@]}" ; do
    hc add "${tag_names[$i]}"
    key="${tag_keys[$i]}"
    if [ -n "$key" ] ; then
        hc keybind "$Mod-$key" use_index "$i"
        hc keybind "$Mod-Shift-$key" move_index "$i"
    fi
done


hc keybind $Mod-Shift-e quit
hc keybind $Mod-Shift-r reload
hc keybind $Mod-Shift-q close

# layouting
hc keybind $Mod-x remove
hc keybind $Mod-s floating toggle
hc keybind $Mod-f fullscreen toggle
hc keybind $Mod-space set_attr clients.focus.floating toggle
hc keybind $Mod-m set_attr clients.focus.minimized true
hc keybind $Mod-Shift-m jumpto last-minimized


# The following cycles through the available layouts within a frame, but skips
# layouts, if the layout change wouldn't affect the actual window positions.
# I.e. if there are two windows within a frame, the grid layout is skipped.
hc keybind $Mod-Tab                                                           \
            or , and . compare tags.focus.curframe_wcount = 2                   \
                     . cycle_layout +1 vertical horizontal max grid    \
               , cycle_layout +1
# mouse
hc mouseunbind --all
hc mousebind $Mod-Button1 move
hc mousebind $Mod-Button2 zoom
hc mousebind $Mod-Button3 resize


# theme
hc attr theme.tiling.reset 1
hc attr theme.floating.reset 1

hc set show_frame_decorations 'none'
hc set frame_transparent_width 1
hc set frame_gap 0

hc attr theme.active.color $ORANGE
hc attr theme.active.inner_color $ORANGE
hc attr theme.normal.color $GREY
hc attr theme.normal.inner_color $GREY
hc attr theme.urgent.color $CYAN
hc attr theme.urgent.inner_color $CYAN

hc attr theme.inner_width 0
hc attr theme.border_width 2

hc attr theme.floating.border_width 2
hc attr theme.floating.outer_width 0

hc set window_gap 4
hc set frame_padding 6
hc set smart_window_surroundings off
hc set smart_frame_surroundings borders
hc set mouse_recenter_gap 0

# rules
hc unrule -F
hc rule focus=on # normally focus new clients
hc rule floatplacement=smart
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(DIALOG|UTILITY|SPLASH)' floating=on
hc rule windowtype='_NET_WM_WINDOW_TYPE_DIALOG' focus=on
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(NOTIFICATION|DOCK|DESKTOP)' manage=off
hc rule fixedsize floating=on
hc set tree_style '╾│ ├└╼─┐'

# unlock, just to be sure
hc unlock

# do multi monitor setup here, e.g.:
# hc set_monitors 1280x1024+0+0 1280x1024+1280+0
hc detect_monitors


# find the panel
#panel=~/.config/herbstluftwm/lauch.sh
#[ -x "$panel" ] || panel=/etc/xdg/herbstluftwm/panel.sh
#for monitor in $(hc list_monitors | cut -d: -f1) ; do
#    # start it on each monitor
#    "$panel" "$monitor" &
#done
