#! /bin/sh

Terminal="xfce4-terminal"
Filemanager="pcmanfm"
Rofi="rofi -modi drun,run -show drun -icon-theme 'Papirus-Dark' -show-icons"
Lock="slock"
UpVol="amixer -q sset Master 2%+ unmute"
DownVol="amixer -q sset Master 2%- unmute"
Screenshot="xfce4-screenshooter -f"
WScreenshot="xfce4-screenshooter -w"
SScreenshot="xfce4-screenshooter -r"

cat << SXHKDFILE > /tmp/sxhkd
# apps
super + Return
	${Terminal}

super + r
	${Rofi}

super + e
	${Filemanager}

super + l
	${Lock}

F8
	${UpVol}

F7
	${DownVol}

F10
	${Screenshot}

ctrl + F10
	${SScreenshot}

alt + F10
	${WScreenshot}

# bspwm hotkeys

# quit/restart bspwm
super + shift + {e,r}
	bspc {quit,wm -r}

# close and kill
super + {ctrl +,shift + }q
	bspc node -{k,c}

# alternate between the tiled and monocle layout
super + Tab
	bspc desktop -l next

# send the newest marked node to the newest preselected node
super + y
	bspc node newest.marked.local -n newest.!automatic.local

# swap the current node and the biggest window
super + g
	bspc node -s biggest.window

# state/flags

# set the window state
super + {t,shift + t,space,f}
	bspc node -t {tiled,pseudo_tiled,floating,fullscreen}

# set the node flags
super + ctrl + {m,x,y,z}
	bspc node -g {marked,locked,sticky,private}

# focus/swap

# focus the node in the given direction
super + {Left,Down,Up,Right}
	bspc node -f {prev.local.!hidden.window,south,north,next.local.!hidden.window}

# focus the node in the given direction
super + shift + {Left,Down,Up,Right}
	bspc node -s {west,south,north,east}

# focus the node for the given path jump
super + {p,b,comma,period}
	bspc node -f @{parent,brother,first,second}

# focus the next/previous window in the current desktop
super + {_,shift + }c
	bspc node -f {next,prev}.local.!hidden.window

# focus the next/previous desktop in the current monitor
super + bracket{left,right}
	bspc desktop -f {prev,next}.local

# focus the last node/desktop
#super + {grave,Tab}
#	bspc {node,desktop} -f last

# focus the older or newer node in the focus history
#super + {o,i}
#	bspc wm -h off; \
#	bspc node {older,newer} -f; \
#	bspc wm -h on

# focus or send to the given desktop
super + {_,shift + }{1-9,0}
	bspc {desktop -f,node -d} '^{1-9,10}'

# preselect

# preselect the direction
super + ctrl + {Left,Down,Up,Right}
	bspc node -p {west,south,north,east}

# preselect the ratio
super + ctrl + {1-9}
	bspc node -o 0.{1-9}

# cancel the preselection for the focused node
super + ctrl + space
	bspc node -p cancel

# cancel the preselection for the focused desktop
super + ctrl + shift + space
	bspc query -N -d | xargs -I id -n 1 bspc node id -p cancel

# move/resize

# expand a window by moving one of its side outward
super + alt + {Left,Down,Up,Right}
	bspc node -z {left -20 0,bottom 0 20,top 0 -20,right 20 0}

# contract a window by moving one of its side inward
super + alt + shift + {Left,Down,Up,Right}
	bspc node -z {right -20 0,top 0 20,bottom 0 -20,left 20 0}

SXHKDFILE

xsetroot -cursor_name left_ptr
killall sxhkd; sxhkd -c /tmp/sxhkd &
redshift -P -O 3400 &
killall picom; picom --animations --animation-window-mass 0.5 --animation-stiffness 230.0 --animation-for-open-window zoom --animation-dampening 21.0 &
if xrandr -q | egrep VGA | egrep connected -q; then
	{ xrandr --newmode 1600 118.25  1600 1696 1856 2112  900 903 908 934 -hsync +vsync; xrandr --addmode VGA1 1600; xrandr --output VGA1 --mode 1600 --primary --output LVDS1 --off; } &
fi
nitrogen --restore &
killall lxpolkit; lxpolkit &
bash ~/.config/bspwm/lauch.sh

bspc monitor VGA1 -d I II III IV V VI VII VIII IX X

BLUE="#005577"
CYAN="#1793d1"
ORANGE="#ff9b82"
GREY="#444444"

bspc config normal_frame_opacity 1.0
bspc config focused_frame_opacity 0.05
bspc config focused_border_color ${ORANGE}
bspc config normal_border_color ${GRE}
bspc config presel_border_color ${ORANGE}
bspc config urgent_border_color ${CYAN}
bspc config focused_private_border_color ${BLUE}
bspc config border_width 2
bspc config window_gap          12

bspc config focus_follows_pointer true

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      false

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
