#!/bin/bash
xrandr --newmode 1280x720 74.50  1280 1344 1472 1664  720 723 728 748 -hsync +vsync 
xrandr --addmode VGA1 1280x720
#xrandr --output LVDS1 --mode 1024x600 --output VGA1 --primary --mode 1280x720 --right-of LVDS1
xrandr --output LVDS1 --primary --mode 1024x600 --output VGA1 --mode 1280x720 --right-of LVDS1

nitrogen --restore
