#!/bin/bash

check() {

	( [ $(cat /sys/class/net/w*/operstate) == "down" ] &&
	[ $(cat /sys/class/net/e*/operstate) == "down" ]) && {

		echo "DOWN";
		echo "DOWN";
		exit 33;
	}
}


obtain() {

	local sum=0
	local current=$(echo $(cat /sys/class/net/w*/statistics/${1}_bytes | paste -sd"+") | bc)

: '
	for i in $current; do

		sum=$(echo "$sum + $i" | bc)
	done
'
	cache="$1"

	[ -f $cache ] && old=$(cat $cache) || old=0
	: '
	echo $sum > $cache
	echo "$(( (sum-old) / 1024 ))"
	'
	echo $current > $cache
	echo "$(( (current-old) / 1024 ))"
}

#check

down=$(obtain rx)
up=$(obtain tx)

echo "D ${down}K U ${up}K"
echo "D ${down}K U ${up}K"

exit 0
